[package]
name = "pcl-da"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true


[dependencies]
# PCL deps
pcl-common = { workspace = true }
pcl-phoundry = { workspace = true }
clap = { workspace = true }
thiserror = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }

reqwest = { version = "0.11", features = ["json", "blocking"] }

alloy-primitives = "0.6"

[dev-dependencies]
mockito = "1.2"
