#!/usr/bin/env bash
set -eo pipefail

echo "Installing pclup..."

BASE_DIR="${XDG_CONFIG_HOME:-$HOME}"
PCL_DIR="${PCL_DIR:-"$BASE_DIR/.pcl"}"
PCL_BIN_DIR="$PCL_DIR/bin"
PCL_MAN_DIR="$PCL_DIR/share/man/man1"

BIN_URL="https://raw.githubusercontent.com/phylax-systems/pcl/feat/pclup/pclup/pclup"
BIN_PATH="$PCL_BIN_DIR/pclup"

# Create the .pcl bin directory and pclup binary if it doesn't exist.
mkdir -p "$PCL_BIN_DIR"
curl -sSf -L "$BIN_URL" -o "$BIN_PATH"
chmod +x "$BIN_PATH"

# Create the man directory for future man files if it doesn't exist.
mkdir -p "$PCL_MAN_DIR"

# Store the correct profile file (i.e. .profile for bash or .zshenv for ZSH).
case $SHELL in
*/zsh)
    PROFILE="${ZDOTDIR-"$HOME"}/.zshenv"
    PREF_SHELL=zsh
    ;;
*/bash)
    PROFILE=$HOME/.bashrc
    PREF_SHELL=bash
    ;;
*/fish)
    PROFILE=$HOME/.config/fish/config.fish
    PREF_SHELL=fish
    ;;
*/ash)
    PROFILE=$HOME/.profile
    PREF_SHELL=ash
    ;;
*)
    echo "pclup: could not detect shell, manually add ${PCL_BIN_DIR} to your PATH."
    exit 1
esac

# Only add pclup if it isn't already in PATH.
if [[ ":$PATH:" != *":${PCL_BIN_DIR}:"* ]]; then
    # Add the pclup directory to the path and ensure the old PATH variables remain.
    # If the shell is fish, echo fish_add_path instead of export.
    if [[ "$PREF_SHELL" == "fish" ]]; then
        echo >> "$PROFILE" && echo "fish_add_path -a $PCL_BIN_DIR" >> "$PROFILE"
    else
        echo >> "$PROFILE" && echo "export PATH=\"\$PATH:$PCL_BIN_DIR\"" >> "$PROFILE"
    fi
fi

# Warn MacOS users that they may need to manually install libusb via Homebrew:
if [[ "$OSTYPE" =~ ^darwin ]] && [[ ! -f /usr/local/opt/libusb/lib/libusb-1.0.0.dylib ]] && [[ ! -f /opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib ]]; then
    echo && echo "warning: libusb not found. You may need to install it manually on MacOS via Homebrew (brew install libusb)."
fi

echo
echo "Detected your preferred shell is $PREF_SHELL and added pclup to PATH."
echo "Run 'source $PROFILE' or start a new terminal session to use pclup."
echo "Then, simply run 'pclup' to install PCL." 