[package]
name = "pcl-phoundry"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true


[dependencies]
# PCL deps
pcl-common = { workspace = true }

# Foundry deps
forge = { git = "https://github.com/foundry-rs/foundry", branch = "master" }

clap = { workspace = true }
thiserror = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }