[package]
name = "pcl-phoundry"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true


[dependencies]
clap = { workspace = true }
thiserror = { workspace = true }