[package]
name = "cl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Credible Layer CLI"
default-run = "cl"

[dependencies]

cl-sp1-host.workspace = true

tokio.workspace = true
clap.workspace = true