# release.yml
name: Release

on:
  workflow_run:
    workflows: ["Rust"]
    types:
      - completed

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      startsWith(github.event.workflow_run.head_branch, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Setup ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Initialize Git submodules
        run: git submodule update --init --recursive
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - name: Build Release Binary
        run: make build
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/pcl
            target/release/phorge
          draft: false
          prerelease: false
          generate_release_notes: true
