# blatantly lifted from https://github.com/init4tech/actions/blob/main/.github/workflows/rust-base.yml
name: Rust

on:
  push:
    branches: [main]
  pull_request:

jobs:
  unit-test:
    name: Unit Tests
    runs-on:
      group: ubuntu-latest
    steps:      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly

      - uses: Swatinem/rust-cache@v2

      - uses: taiki-e/install-action@nextest

      - name: Run Unit Tests
        run: make test
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: make format

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Install clippy
        run: rustup component add clippy

      - name: Lint
        run: make lint