name: Rust Build, Test, Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-rust-base-ci:
    name: Run phylax CI
    uses: phylaxsystems/actions/.github/workflows/rust-base.yaml
    with:
      rust-channel: "nightly"
      require-lockfile: true
      install-foundry: true
      submodules: "recursive"
      requires-private-deps: true
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
