name: Rust CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  rust-base:
    uses: phylaxsystems/actions/.github/workflows/rust-base.yaml@main
    with:
      rust-channel: "nightly"
      require-lockfile: true
      submodules: "recursive"
      requires-private-deps: true
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
